profiles/urls.py
from django.urls import path
from . import views


app_name = "profiles"

urlpatterns = [
    path("<str:username>/", views.ProfileDetailView.as_view(), name="detail"),
    path("<str:username>/follow/", views.FollowView.as_view(), name="follow"),
   
]

til/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from feed import urls as feed_urls
from profiles import urls as profiles_urls



urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include(feed_urls, namespace="feed")),
    path("profile/", include(profiles_urls, namespace="profiles")),
    path("", include("allauth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from sorl.thumbnail import ImageField


class Profile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name="profile"
    )
    image = ImageField(upload_to='profiles', blank=True)
    def __str__(self):
        return self.user.username

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    """Create a new Profile() object when a Django user is created"""
    if created:
        Profile.objects.create(user=instance)

profiles/views.py
from django.contrib.auth.models import User
from django.views.generic import DetailView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse, HttpResponseBadRequest

from feed.models import Post
from followers.models import Follower




class ProfileDetailView(DetailView):
    http_method_names = ["get"]
    template_name = "profiles/detail.html"
    model = User
    context_object_name = "user"
    slug_field = "username"
    slug_url_kwarg = "username"

    def dispatch(self, request, *args, **kwargs):
        self.request = request 
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        user = self.get_object()
        context = super().get_context_data(**kwargs)
        context['total_posts'] = Post.objects.filter(author=user).count()
        context['total_followers'] = Follower.objects.filter(following=user).count()
        if self.request.user.is_authenticated:
            context['you_follow'] = Follower.objects.filter(following = user, followed_by = self.request.user).exists()
        return context
    
class FollowView(LoginRequiredMixin, View):
    http_method_names = ["post"]

    def post(self, request, *args, **kwargs):
        data = request.POST.dict()

        if "action" not in data or "username" not in data:
            return HttpResponseBadRequest("Missing data")

        try:
            other_user = User.objects.get(username=data['username'])
        except UserDoesNotExist:
            return HttpResponseBadRequest("Missing user")
        
        if data['action'] == "follow":
            #Follow 
            follower, created = Follower.objects.get_or_create(
                followed_by = request.user,
                following = other_user,
            )
        else:
            #Unfollow
            try:
                follower = Follower.objects.get(
                    followed_by = request.user,
                    following = other_user,
                )
            except Follower.DoesNotExist:
                follower = None
            
            if follower:
                follower.delete()
        return JsonResponse({
            'success' : "True",
            'wording' : "Unfollow" if data['action'] == "follow" else "Follow"
        })

profiles/templates/profiles/detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %} {{ user.username }}{% endblock %}

{% block body %}
     <!-- component -->
    <div class="rounded-3xl overflow-hidden shadow-xl max-w-xs my-3">
        <img src="https://static.vecteezy.com/system/resources/thumbnails/023/669/545/small/abstract-gradient-pink-blue-liquid-wave-background-free-vector.jpg" class="w-full" />
        <div class="flex justify-center -mt-8 bg-white">
            {% thumbnail user.profile.image "150x150" crop="center" as im %}
                <img src="{{ im.url }}" class="rounded-full border-solid border-gray-300 border-2 -mt-3">  
            {% endthumbnail %} 
        </div>
        <div class="text-center px-3 pb-6 pt-2 bg-white">
            <h3 class="text-black text-lg bold font-sans"> <b>{{ user.username }} </b></h3>
            {% if request.user.is_authenticated %}
                {% if request.user != user %}
                    <div class="mt-3">
                        <button class="bg-white text-gray-800 font-bold rounded border-b-2 border-pink-500 hover:border-pinl-600 hover:bg-pink-500 hover:text-white shadow-md py-1 px-3 inline-flex items-center text-sm mt-4 js-follow" data-username = "{{ user.username }}" data-action = "{% if you_follow %}un{% endif %}follow" data-url = "{% url 'profiles:follow' user.username %}" type="button">
                                <span class="mr-2 js-follow-text">
                                    {% if you_follow %}
                                        Unfollow
                                    {% else %}
                                        Follow
                                    {% endif %} </span>
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                                    <path fill="currentcolor" d="M2.01 21L23 12 2.01 3 2 10l15 2-15 2z"></path>
                                </svg>
                        </button>
                    </div>
                {% endif %}
            {% else %}
                <div class="mt-3 text-sm"> Login to follow this user </div>
            {% endif %}
            <p class="mt-2 font-sans font-light text-black"></p> 
        </div>
        <div class="flex justify-center pb-3 text-black bg-gray-300">
        <div class="text-center mr-3 border-r pr-3">
            <h2><b>{{ total_posts }} </b></h2>
            <span><b>Posts </b></span>
        </div>
        <div class="text-center">
            <h2><b>{{ total_followers }}</b></h2>
            <span><b>Followers</b></span>
        </div>
        </div>
    </div>
{% endblock %}

profiles/templates/profiles/profile.html
{% extends "base.html" %}
{% block title %}Profile Page{% endblock title %}
{% block content %}
    <div>
        <h1>This is the profile page for {{user.username}}</h1>
    </div>

{% endblock content %}