feed/urls.py
from django.urls import path
from . import views



app_name = "feed"
urlpatterns = [
    path("", views.HomePage.as_view(), name="feed.index"),
    path("<int:pk>/", views.PostDetailView.as_view(), name="detail"),
    path("new/", views.CreateNewPost.as_view(), name="new_post"),
    path('post/', views.AddPostView.as_view(), name='new_postim'),
    path('profile_view/', views.ViewProfile, name='profile_view'),
    path('profile_view/edit/', views.EditProfile, name='profile_edit'),
    path('profile_view/edit/change_password/', views.change_password, name='change_password'),
    path('profile_view/edit/change_image/', views.change_image, name='change_image'),
    path('search_venues/', views.search_venues, name='search-venues'),
]

profiles/urls.py
from django.urls import path
from . import views


app_name = "profiles"

urlpatterns = [
    path("<str:username>/", views.ProfileDetailView.as_view(), name="detail"),
    path("<str:username>/follow/", views.FollowView.as_view(), name="follow"),
   
]

til/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from feed import urls as feed_urls
from profiles import urls as profiles_urls



urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include(feed_urls, namespace="feed")),
    path("profile/", include(profiles_urls, namespace="profiles")),
    path("", include("allauth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feed/models.py
from django.db import models
from django.contrib.auth.models import User
from sorl.thumbnail import ImageField





class Post(models.Model):
    text = models.CharField(max_length=240)
    date = models.DateTimeField(auto_now=True)
    image = ImageField()
    author = models.ForeignKey(
        User,
        on_delete = models.CASCADE,
    )

    def __str__(self):
        return self.text[0:100]



def compress(image):
    im = Image.open(image)
    out_put_size = (300,300)
    im.thumbnail(out_put_size)
    # create a BytesIO object
    im_io = BytesIO() 
    # save image to BytesIO object
    im = im.resize([500,500])
    #resize image
    im = im.convert("RGB")
    im = im.save(im_io,'JPEG', quality=50) 
    # create a django-friendly Files object
    new_image = File(im_io, name=image.name)
    return new_image

class Profile(models.Model):
    image = models.ImageField(default='default.jpg', upload_to='profiles')
    
    def save(self, *args, **kwargs):
      #image compression start
      if self.image:
         # call the compress function
         new_image = compress(self.image)
         # set self.image to new_image
         self.image = new_image
      #image compression end 
      super(Profile,self).save(*args, **kwargs)

profiles/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from sorl.thumbnail import ImageField


class Profile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name="profile"
    )
    image = ImageField(upload_to='profiles', blank=True)
    def __str__(self):
        return self.user.username

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    """Create a new Profile() object when a Django user is created"""
    if created:
        Profile.objects.create(user=instance)

feed/forms.py
from django import forms
from django.contrib.auth.forms import  UserChangeForm
from django.contrib.auth.models import User
from .models import Profile
from sorl.thumbnail import ImageField
from django.db import models


class PostForm(forms.Form):
    text = forms.CharField()
    image = forms.FileField()


class EditProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = (
            'email',
            'username',
            'first_name',
            'last_name',
        )

class ProfileUpdateForm(forms.ModelForm):
    image= models.ImageField(upload_to='profiles', blank=True, null=True)
    class Meta:
        model = Profile
        fields = ['image']

feed/views.py
from django.views.generic import ListView, DetailView, CreateView, FormView
from .models import Post
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from .forms import PostForm, EditProfileForm

# from django.shortcuts import render, redirect
# from django.contrib import messages
# from django.contrib.auth.decorators import login_required

from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth.models import User
from django.contrib.auth import update_session_auth_hash
# from .forms import ImageForm
from .forms import ProfileUpdateForm





class HomePage(ListView):
    http_method_names = ["get"]
    template_name = "feed/homepage.html"
    model = Post
    context_object_name = "posts"
    queryset = Post.objects.all().order_by('-id')[0:30]

class PostDetailView(DetailView):
    http_method_names = ["get"]
    template_name = "feed/detail.html"
    model = Post
    context_object_name = "post"

class CreateNewPost(CreateView):
    model = Post
    template_name = "feed/create.html"
    fields = ['text']
    success_url = "/"

    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)
    
    def form_valid(self, form):
        obj = form.save(commit = False)
        obj.author = self.request.user
        obj.save()
        return super().form_valid(form)
    
    def post(self, request, *args, **kwargs):
        post = Post.objects.create(
            text = request.POST.get("text"),
            author = request.user,
        )
        return render(
            request,
            "includes/post.html",
            {
                "post": post,
                "show_detail_link": True,
            },
            content_type = "application/html"
        )
    
class AddPostView(FormView):
    template_name = "feed/new_post.html"
    form_class=PostForm
    success_url = "/"
    
    def form_valid(self, form):
        # Create a new Post
        new_object = Post.objects.create(
            text=form.cleaned_data['text'],
            image=form.cleaned_data['image'],
            author = self.request.user
        )
        return super().form_valid(form)




def ViewProfile(request):
    args = {'user': request.user}
    return render(request, "feed/profile_view.html", args)

def EditProfile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect('/profile_view')
    else:
        form = EditProfileForm(instance=request.user)
        args = {'form': form}
        return render(request, 'feed/profile_edit.html', args)
    

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('/profile_view')
        else:
            return redirect('/profile_view/edit/change_password')
    
    else:
        form = PasswordChangeForm(user=request.user)
        args = {'form': form}
        return render(request, 'feed/change_password.html', args)
    

def change_image(request):
    if request.method == 'POST':
        form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)

        if form.is_valid():
            form.save()
            # update_session_auth_hash(request, form.user)
            return redirect('/profile_view')
        else:
            return redirect('/profile_view/edit/change_image')
    
    else:
        form = ProfileUpdateForm(instance=request.user.profile)
        args = {'form': form}
        return render(request, 'feed/change_image.html', args)



def search_venues(request):
    model = User
    # context_object_name = 'all_search_results'
    if request.method == 'POST':
        user_name = request.POST['user_name']
        usernames = User.objects.filter(username__contains=user_name)
        return render(request, 'feed/search_venues.html', {'user_name':user_name, 'usernames':usernames})
    else:
        return render(request, 'feed/search_venues.html', {})
    

profiles/views.py
from django.contrib.auth.models import User
from django.views.generic import DetailView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse, HttpResponseBadRequest

from feed.models import Post
from followers.models import Follower




class ProfileDetailView(DetailView):
    http_method_names = ["get"]
    template_name = "profiles/detail.html"
    model = User
    context_object_name = "user"
    slug_field = "username"
    slug_url_kwarg = "username"

    def dispatch(self, request, *args, **kwargs):
        self.request = request 
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        user = self.get_object()
        context = super().get_context_data(**kwargs)
        context['total_posts'] = Post.objects.filter(author=user).count()
        context['total_followers'] = Follower.objects.filter(following=user).count()
        if self.request.user.is_authenticated:
            context['you_follow'] = Follower.objects.filter(following = user, followed_by = self.request.user).exists()
        return context
    
class FollowView(LoginRequiredMixin, View):
    http_method_names = ["post"]

    def post(self, request, *args, **kwargs):
        data = request.POST.dict()

        if "action" not in data or "username" not in data:
            return HttpResponseBadRequest("Missing data")

        try:
            other_user = User.objects.get(username=data['username'])
        except UserDoesNotExist:
            return HttpResponseBadRequest("Missing user")
        
        if data['action'] == "follow":
            #Follow 
            follower, created = Follower.objects.get_or_create(
                followed_by = request.user,
                following = other_user,
            )
        else:
            #Unfollow
            try:
                follower = Follower.objects.get(
                    followed_by = request.user,
                    following = other_user,
                )
            except Follower.DoesNotExist:
                follower = None
            
            if follower:
                follower.delete()
        return JsonResponse({
            'success' : "True",
            'wording' : "Unfollow" if data['action'] == "follow" else "Follow"
        })

feed/templates/feed/change_image.html
{% extends "base.html" %}
{% load thumbnail %}


{% block title %} {{ user.username }} {% endblock %}

{% block body %}
    <div class="flex">
    <div class="flex flex-col justify-between items-center w-full border-2 bg-green-100 text-xs md:text-xl" style="background-color: #e8cd99;">
        <div class="w-full"><form class="p-0 md:p-10" method = "post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        </div>
            <div class="flex justify-between items-center text-center"> 
                <button class="bg-gray-400 text-gray-800 content-center font-bold rounded border-b-2 border-pink-500 hover:border-pink-600 hover:bg-pink-400 hover:text-white shadow-md py-2 px-4 inline-flex items-center text-sm" type="submit" style="margin:10px auto;"> Upload</button>
            </div>
        </form> 
   
    </div>
    </div>

{% endblock %}

 

feed/templates/feed/change_password.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %} {{ user.username }} {% endblock %}

{% block body %} 
    <div class="container border-2 text-center text-base md:text-xl" style="background-color: #e8cd99; margin:1px auto;">
        <i><form class="border-1 pt-4 px-2" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="mb-6 bg-gray-400 text-gray-800 content-center font-bold rounded border-b-2 border-green-500 hover:border-green-600 hover:bg-green-400 hover:text-white shadow-md py-2 px-4 inline-flex items-center text-sm mt-6" type="submit"> Submit </button>
        </form></i>
        
    </div>
{% endblock %}

feed/templates/feed/create.html
{% extends "base.html" %}
{% block title %} Create a new post {% endblock title%}

{% block body %}
    <form method="POST" action=".">
        {% csrf_token %}
        {{form.as_p}} 
    <div>
        <div class="my-3">
            <button class="bg-white text-gray-800 font-bold rounded border-b-2 border-green-500 hover:border-green-600 hover:bg-green-500 hover:text-white shadow-md py-2 px-6 inline-flex items-center" type="submit">
                <span class="mr-2">Create Post</span>
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                    <path fill="currentcolor" d="M2.01 21L23 12 2.01 3 2 10l15 2-15 2z"></path>
                </svg>
            </button>
        </div>
    </div>
{% endblock %}

feed/templates/feed/detail.html
{% extends "base.html" %}

{% block title %}{{ post.text }} by {{ post.author.username }}{% endblock %}

{% block body %}
    {% include "includes/post.html" with post=post %}
{% endblock body %}

feed/templates/feed/homepage.html
{% extends "base.html" %}
{% load thumbnail %}


{% block title %}Change the title of the homepage{% endblock %}

{% block body %}
    {% if request.user.is_authenticated %}
     <div class="searchbar mb-8">
            <form class="example" method="POST" action="{% url 'feed:search-venues' %}">
            {% csrf_token %}
                <input type="text" id="search" class="search" placeholder="Search profiles" name="user_name" style="border: 1px solid gray;">
                    <button id="SearchButton" class="bg-gray-400 text-gray-800 content-center font-bold rounded border-b-2 border-pink-500 hover:border-pink-600 hover:bg-pink-400 hover:text-white shadow-md py-1 px-1 inline-flex items-center text-sm mt-6 js-sub" type="submit">
                        Search
                    </button>      
            </form>
    </div>
    {% else %}
        <div class="flex flex-col justify-between text-center">
            <b><h1 class="text-3xl md:text-4xl text-center capitalize mb-10" style="color:rgb(52, 50, 50)">Welcome to TIL app</h1></b>
            <div class="rounded-full">
                <img src="https://img.freepik.com/free-vector/social-media-design-concept_1284-5151.jpg" alt="some" class=""style="border: 2px solid gray;">
            </div>
        </div>
    {% endif %} 
    <div id="posts-container">
        {% for post in posts %}
            {% include "includes/post.html" with post=post show_detail_link=True %} <br>
        {% endfor %}
    </div>

 {% endblock %}

feed/templates/feed/new_post.html
{% extends "base.html" %}

{% block title %} Upload a new image {% endblock %}

{% block body %}
    <div class="flex flex-row text-center text-base md:text-xl" style="margin:1px auto; text-align:center;">
        <form class="basis-9/12 text-sm md:text-xl text-center my-4 content-center p-0 md:p-6" method="POST" action="" enctype="multipart/form-data">
            <h3 class="my-4 content-center text-center text-lg md:text-2xl mb-6"> <b>Upload an image</b></h3>
            {% csrf_token %}
            {{ form.as_p }}
            <div>
                <button class="content-center bg-gray-300 text-gray-800 font-bold rounded border-b-2 border-pink-500 hover:border-pink-600 hover:bg-pink-400 hover:text-white shadow-md py-1 md:py-2 px-2 md:px-4 inline-flex items-center text-sm mt-6" type="submit">
                    <span class="mr-2 text-sm md:text-lg">Submit form </span>
                </button>
            </div>
        </form>
    </div>

{% endblock %}

feed/templates/feed/profile_edit.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %} {{ user.username }} {% endblock %}

{% block body %} 
    <div class="container" style="background-color: #e8cd99;">
        <i><form class="border-2" style="background-color: #e8cd99;" method="post">
            {% csrf_token %}
            {{ form.as_p }}
        <div class="flex flex-col flex items-center"> <button class="bg-gray-400 text-gray-800 content-center font-bold rounded border-b-2 border-green-500 hover:border-green-600 hover:bg-green-400 hover:text-white shadow-md py-2 px-4 inline-flex items-center text-sm mt-6 mb-6" type="submit"> Submit </button> </div>
        </form></i>
    </div>
        <div class="flex flex-col flex items-center border-2" style="background-color: rgb(219, 165, 165)"> 
           <div> <button class="mx-auto bg-gray-400 text-gray-800 content-center font-bold rounded border-b-2 border-green-500 hover:border-green-600 hover:bg-green-400 hover:text-white shadow-md py-2 px-6 inline-flex items-center text-sm mt-6" type="button"> <a href="{% url 'feed:change_password' %}" span class="mr-2 text-sm md:text-base"> Change Password </button> </div>

           <div> <button class="mx-auto bg-gray-400 text-gray-800 content-center font-bold rounded border-b-2 border-green-500 hover:border-green-600 hover:bg-green-400 hover:text-white shadow-md py-2 px-2 inline-flex items-center text-sm mt-6 mb-6" type="button"> <a href="{% url 'feed:change_image' %}" span class="mr-2 text-sm md:text-base"> Change Profile Image </button> </div>         
        </div>
        
{% endblock %}

feed/templates/feed/profile_view.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %} {{ user.username }} {% endblock %}

{% block body %} 
    <div class="container bg-orange-200">
        <h1 class="my-4 text-center text-2xl md:text-3xl" style="text-shadow: 2px 2px 2px white; color: gray"> <u> <b> My Profile </b> </u> <h1>
        <p class="my-3 text-center md:text-left text-base md:text-xl"> 
            <b> Username: </b> {{ user.username }} 
        </p>
        <p class="my-3 text-center md:text-left text-base md:text-xl"> 
            <b> First name: </b> {{ user.first_name }} 
        </p>
        <p class="my-3 text-center md:text-left text-base md:text-xl"> 
            <b> Last name: </b> {{ user.last_name }} 
        </p>
        <p class="my-3 text-center md:text-left text-base md:text-xl"> 
            <b> Email: </b> {{ user.email }} 
        </p>
        <div class="my-4 text-center md:text-left text-base md:text-xl"> 
            <b> Profile image: </b> 
        </div>
        <div class="my-6"> 
            {% thumbnail user.profile.image "150x150" crop="center" as im %}
                <img src="{{ im.url }}" class="rounded-full border-solid border-gray-300 border-2 -mt-3">  
            {% endthumbnail %} 
        </div> 
    </div>
    <button class="bg-gray-400 text-gray-800 font-bold rounded border-b-2 border-white-500 hover:border-white hover:bg-pink-400 hover:text-white shadow-md py-2 px-4 inline-flex items-center text-sm mt-6" type="button">
        <a href="{% url 'feed:profile_edit' %}" span class="mr-2 text-lg">Profile settings </span>
    </button>
{% endblock %}

feed/templates/feed/search_venues.html
{% extends "base.html" %}

{% block body %}

    {% if user_name %}
        <div class="py-10 text-center text-lg md:text-xl" style="font-size:20px;">You searched for: </div>
            {% for username in usernames %}
                <div class="text-center text-xl md:text-2xl" style="color:rgba(50, 25, 213, 0.5); font-size: 30px;"><b> <u> <a href = "{% url 'profiles:detail' username %}">{{ username}} </a> </u> </b> </div> <br/> 
                {% empty %}
                  <p style="text-align:center; font-size: 20px;"><b>  no results </b></p>
            {% endfor %}
    {% else %}
        <h1> You forgot to search fo a venue </h1>
    {% endif %}
    
{% endblock %}