feed/urls.py
from django.urls import path
from . import views



app_name = "feed"
urlpatterns = [
    path("", views.HomePage.as_view(), name="feed.index"),
    path("<int:pk>/", views.PostDetailView.as_view(), name="detail"),
    path("new/", views.CreateNewPost.as_view(), name="new_post"),
    path('post/', views.AddPostView.as_view(), name='new_postim'),
    path('profile_view/', views.ViewProfile, name='profile_view'),
    path('profile_view/edit/', views.EditProfile, name='profile_edit'),
    path('profile_view/edit/change_password/', views.change_password, name='change_password'),
    path('profile_view/edit/change_image/', views.change_image, name='change_image'),
    path('search_venues/', views.search_venues, name='search-venues'),
]

til/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from feed import urls as feed_urls
from profiles import urls as profiles_urls



urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include(feed_urls, namespace="feed")),
    path("profile/", include(profiles_urls, namespace="profiles")),
    path("", include("allauth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

til/templates/includes/post.html
{% load thumbnail %}
{% comment %} {{ post.text }} {% endcomment %}
    <!-- component -->
{% if request.user.is_authenticated %}
    {% comment %} <div class="md:w-4xl px-10 my-4 py-6 bg-pink-100 rounded-lg shadow-md" style = "width: 50rem"> {% endcomment %}
    <div class="sm:w-full px-3 md:px-10 my-4 py-6 rounded-lg shadow-md" style="background-color: rgb(240, 193, 138);">
        <div class="flex justify-between items-center">
            <span class="text-sm md:text-base text-center sm:text-center font-light text-gray-600">{{ post.date|date:"F, j, Y, g:i:a" }}</span>
            {% comment %} <a class="px-2 py-1 bg-gray-600 text-gray-100 font-bold rounded hover:bg-gray-500" href="#">Design</a> {% endcomment %}
        </div>
        <div class="mt-2">
            <p class="text-sm md:text-base text-justify md:text-left mt-2 text-gray-600"><b>{{ post.text }}</b></p>
        </div>
        <div class="mt-2">
            {% thumbnail post.image "200x200" crop="center" as im %}
                <img src="{{ im.url }}" class="card-img-top" alt="...">
            {% endthumbnail %}
        </div>
        <div class="flex justify-between items-baseline md:items-center">
            {% if show_detail_link %}
                <a class="text-sm md:text-base text-pink-600 hover:underline" href="{% url 'feed:detail' post.id %}">Read more</a>
            {% else %}
                <span>&nbsp;</span>
            {% endif %}
            <div>
                <a class="flex items-center flex flex-col md:flex-row" href="{% url 'profiles:detail' post.author.username %}">
                {% thumbnail post.author.profile.image "100x100" crop="center" as im %}
                    <img class="mx-1 my-1 w-10 h-10 object-cover rounded-full " src="{{ im.url }}" alt="avatar">
                {% endthumbnail %}    
                    <h1 class="text-sm md:text-base text-gray-700 font-bold">{{ post.author.username }}</h1>
                </a>
            </div>
        </div>
    </div>
{% endif %}