feed/urls.py
from django.urls import path
from . import views



app_name = "feed"
urlpatterns = [
    path("", views.HomePage.as_view(), name="feed.index"),
    path("<int:pk>/", views.PostDetailView.as_view(), name="detail"),
    path("new/", views.CreateNewPost.as_view(), name="new_post"),
    path('post/', views.AddPostView.as_view(), name='new_postim'),
    path('profile_view/', views.ViewProfile, name='profile_view'),
    path('profile_view/edit/', views.EditProfile, name='profile_edit'),
    path('profile_view/edit/change_password/', views.change_password, name='change_password'),
    path('profile_view/edit/change_image/', views.change_image, name='change_image'),
    path('search_venues/', views.search_venues, name='search-venues'),
]

til/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from feed import urls as feed_urls
from profiles import urls as profiles_urls



urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include(feed_urls, namespace="feed")),
    path("profile/", include(profiles_urls, namespace="profiles")),
    path("", include("allauth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

til/templates/base.html
{% load static %}
{% load thumbnail %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Default tile in here{% endblock %}</title>
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet"> 
    <link rel="stylesheet" href="https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css" />

   
</head>
<body>



 <div class="min-h-screen flex flex-row" style="background-color:bisque;">
  {% comment %} <div class="flex flex-col w-56 bg-gray-800 rounded-r-3xl overflow-hidden"> {% endcomment %}
  <div class="flex flex-col w-56 bg-gray-800 rounded-r-3xl">
    <div class="flex flex items-center justify-center h-20 shadow-md">
      <h1 class="text-3xl uppercase text-pink-500" style="color: rgb(240, 193, 138)">TIL</h1>
    </div>
    <ul class="flex flex-col py-4">
      {% if request.user.is_authenticated %}
      <li>
        <a href="{% url 'feed:profile_view' %}" class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-white hover:text-gray-400">
          <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-white-400"><i class="bx bxs-user-rectangle"></i></span>
          <span class="text-base text-center md:text-sm font-medium mr-1 ">My profile</span>
        </a>
      </li>
      <li>
        <a href="/" class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-white hover:text-gray-400">
          <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-white-400"><i class="bx bx-home"></i></span>
          <span class="text-base text-center md:text-sm font-medium mr-1">Home</span>
        </a>
      </li>
      <li>
        <a href="{% url 'feed:new_post' %}" class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-white hover:text-gray-400 js-toggle-modal">
          <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-white-400"><i class="bx bx-layer-plus"></i></span>
          <span class="text-base text-center md:text-sm font-medium mr-1"> New post </span>
        </a>
      </li>
      <li>
        <a href="{% url 'feed:new_postim' %}" class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-white hover:text-gray-400">
          <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-white-400"><i class="bx bx-layer-plus"></i></span>
          <span class="text-base text-center md:text-sm font-medium mr-1"> Upload image </span> 
        </a>
      </li>
      <li>
        <a href="{% url 'account_logout' %}" class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-white hover:text-gray-400">
          <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-white-400"><i class="bx bx-log-out"></i></span>
          <span class="text-base text-center md:text-sm font-medium mr-2">Logout</span>
        </a>
      </li>
      {% else %}
      <li>
        <a href="{% url 'account_login' %}" class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-white hover:text-gray-400">
          <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-white-400"><i class="bx bx-log-in"></i></span>
          <span class="text-base text-center md:text-sm font-medium mr-2">Login</span>
        </a>
      </li>
      {% endif %}
    </ul>
  </div>
  <div class ="p-16">
     {% block body %}
        {% block content %}{% endblock %}
    {% endblock %}
  </div>
  <!-- component -->
  {% if request.user.is_authenticated %}
    <div class="flex items-center justify-center fixed left-0 bottom-0 w-full h-full bg-gray-800 bg-opacity-75 hidden js-modal">
      <div class="bg-white rounded-lg w-10/12 md:w-1/2" style="background-color:rgb(236, 235, 202)">
        <div class="flex flex-col items-start p-1">
          <div class="flex items-center w-full">
            <div class="text-gray-900 font-medium text-lg" style="color:black; font-size:25px;" >New post</div>
        <svg class="ml-auto fill-current text-gray-700 w-6 h-6 cursor-pointer js-toggle-modal" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 18 18">
          <path d="M14.53 4.53l-1.06-1.06L9 7.94 4.53 3.47 3.47 4.53 7.94 9l-4.47 4.47 1.06 1.06L9 10.06l4.47 4.47 1.06-1.06L10.06 9z"/>
          </svg>
          </div>
          <hr>
          <div class="w-full">
            <textarea class="border-2 my-4 w-full js-post-text" style="border:3px solid rgb(122, 84, 62)" ; " placeholder="Enter your post" rows="4" maxlength="240" data-post-url="{% url 'feed:new_post' %}"> </textarea>
          </div>
          <hr>
          <div class="ml-auto">
            <button class=" text-gray-800 font-bold rounded border-b-2 border-pink-500 hover:border-pink-600 hover:bg-pink-400 hover:text-black shadow-md py-1 px-3 inline-flex items-center text-sm mt-4 js-submit" style="background-color:rgb(209, 207, 165); border-bottom: 2px solid rgb(122, 84, 62)" type="button">
                    <span class="mr-2">Create Post</span>
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                        <path fill="currentcolor" d="M2.01 21L23 12 2.01 3 2 10l15 2-15 2z"></path>
                    </svg>
            </button>
          </div>
        </div>
      </div>
    </div>
  {% endif %}
</div> 






</div>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script src="{% static 'js/main.js' %}"> </script>
</body>
</html>